### PR TITLE
Fix typos in Part I and Part II notes

### PR DESCRIPTION
**Pull request by pitmonticone**

### CODE REVIEW

**Comment by zeramorphic** [comment]
Thank you very much for these fixes. Out of interest, how did you find these errors - was it manual, or using a tool? I'd like to see if it's possible to automate these kinds of checks.

**Comment by pitmonticone** [comment]
Hi @Datseris, 

You're welcome. I'm more than pleased to contribute to a resource that I find valuable. 

To answer your question, here is my "workflow":
1. I found the repository quite useful and decided that contributing would be a good way to give a bit back.
2. Textual revision, editing ad code testing are activities I particularly enjoy, especially when I am traveling or boringly awaiting.
3. While consulting the parts of the content most relevant to me, I took the opportunity to manually correct typos (via smartphone in too many cases haha). 
4. My contribution is obviously contingent on my available time. Typically, if I manually identify more than 5/6 errors—be they in text syntax, text semantics, code syntax, or code semantics—I opt to contribute by: 
   - running a global "find and replace" for all mistakes I've manually found locally;
   - using the default spell-checker (e.g. Overleaf) to complete the job.
   
Hope it's helpful.

**Comment by pitmonticone** [comment]
Hi @zeramorphic , 

You're welcome. I'm more than pleased to contribute to a resource that I find valuable. 

To answer your question, here is my "workflow":
1. I found the repository quite useful and decided that contributing would be a good way to give a bit back.
2. Textual revision, editing ad code testing are activities I particularly enjoy, especially when I am traveling or boringly awaiting.
3. While consulting the parts of the content most relevant to me, I took the opportunity to manually correct typos (via smartphone in too many cases haha). 
4. My contribution is obviously contingent on my available time. Typically, if I manually identify more than 5/6 errors—be they in text syntax, text semantics, code syntax, or code semantics—I opt to contribute by: 
   - running a global "find and replace" for all mistakes I've manually found locally;
   - using the default spell-checker (e.g. Overleaf) to complete the job.
   
Hope it's helpful.

**Comment by zeramorphic** [comment]
Thanks, this is really helpful!

**Pull request merged**
